[feat] #1 - 1주차 과제 구현
AND-SOPT-ANDROID/seho-park pull request #2
Opened 2024-10-11 13:30 UTC by sayyyho

## Related issue 🛠
- closed #1 

## Work Description ✏️
- 회원가입 화면 및 기능 구현
- 로그인 화면 및 기능 구현
- 마이페이지 화면

## Screenshot 📸

https://github.com/user-attachments/assets/06d0e50a-e2d9-4cb4-bf92-282c16ed72e0

## Uncompleted Tasks 😅
- [ ] 초기 요구사항 UI
- [ ] 자동 로그인 기능 구현
- [ ] 스택 관리
- [ ] 클릭 시 리플효과
- [ ] 2줄 방지 + 엔터 클릭 시 다음 입력칸으로 넘어가도록 구현

## To Reviewers 📢
> 처음 안드로이드를 접해봐서 힘들었는데, 최대한 구현하려고 노력했습니다. 
처음 배우는 입장에서 코드리뷰를 받을 수 있어 영광입니다 🥹🥹

2024-10-13 08:32 UTC, kez-lab reviewed
안녕하세요 세호님 코드리뷰를 담당하게된 명예OB 곽의진입니다. 반갑습니다 ㅎㅎ 

안드로이드가 처음이시라고 하셨는데 이렇게 기능을 하는 앱을 벌써 제작하시다니 대단하십니다! 여러모로 신경쓸게 많은 안드로이드다보니 어려운 부분들도 많으시겠지만 OB분들 코드를 많이 훔쳐보시면서 어떤 점이 다른지 왜 저렇게 개발했는지 살펴보신다면 많은 도움이 되실겁니다.

전반적으로 비밀번호 가시성이라던가 MyActivity에 재밌는 요소를 추가하신 것을 보니 UI구성하면서 많은 고민과 다양한 아이디어를 직접 도입한 적극적인 부분이 인상깊었습니다.

리뷰는 전반적으로 UI 및 기능 개발의 기본적인 내용보다는 한단계 더 생각해보고 개발하신 부분을 캐치해볼려고 노력했는데요. 혹시나 이해 안가시는 부분이 있다면 리뷰 달아주시면 바로 대응하겠습니다!

1주차 과제 너무 고생하셨습니다!!

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +        }
Icon에 Clickable을 활용한 컴포넌트도 있고 IconButton을 활용하시기도 하셨는데 이렇게 구분되어 활용된 이유가 있을까요?

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +            }
요기서 UI를 전부 초기화 하는 것이 아닌 email과 password의 상태를 변경해줌에 따라 리컴포지션을 발생시키는 방법은 어떨까요?

지금과 같은 구조는 명령형 UI에  가까운 것 같습니다! 선언형 UI인 컴포즈의 장점을 활용해보시면 좋을 것 같아요

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                val password = intent.getStringExtra("password") ?: ""
```suggestion
            ANDANDROIDTheme {
                val email = intent.getStringExtra("email").orEmpty()
                val password = intent.getStringExtra("password").orEmpty()
```

이런 함수도 있어요!

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +        )
요거 아이콘과 같은 이미지 리소스를 넣어두는 게 더 잘어울릴 것 같아요!
그리고 < 를 클릭했을 때 뒤로가거나 화면을 종료하는 액션이 따로 없는 것 같네요

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                singleLine = true,
요런 문자열은 리소스로 따로 분리하는 습관을 들이면 좋을 겁니다.
1. 재사용성
2. 오타 등의 실수 방지
3. 현지화 -> 언어를 영어로 바꾸면 영문 string 파일로 참조가 가능합니다.

물론 지금과 같은 상황에서는 위 3가지 측면 모두 실질적으로 필요하지 않을 수 있어요. 이런 장점이 있다~ 정도만 알고계셔도 좋을 것 같습니다

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                    }
as와 같은 type casting 을 진행할 때는 as? 로 안전하게 형변환을 진행하는 것을 추천드립니다. 만약 다른 type이라면 런타임 크래시가 발생하고 앱은 강제종료될거에요

2024-10-13 08:32 UTC, kez-lab commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                    }
추가적으로 LocalContext.current의 타입을 더 상위 타입인 ComponentActivity 또는 Activity로 변환하는게 위 컴포저블을 재사용한다는 측면에서도 좋을 것 같네요. SignIn컴포저블은 public fun이니까요

2024-10-13 08:32 UTC, kez-lab commented on gradle/libs.versions.toml
해당 라이브러리를 추가하신 이유가 있으실까요?

2024-10-13 10:50 UTC, imtaejugkim approved these changes
같은 compose 처음 하는 입장에서 UI 작하셨던 코드를 보고 정말 고뇌의 흔적들이 느껴졌습니다..!이번 SOPT 동안 같이 많이 배워가요 아자아자!

2024-10-13 10:50 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun validateEmail(email: String): Boolean {
저도 이메일 유효성을 다음과 같이 정의했는데요! r기능 중에 Patterns.EMAIL_ADDRESS.matches()를 통해 쉽게 이메일 형식을 검증해주는 기능이 있더라고요! 한번 이용해 보셔도 좋을 것 같습니다

2024-10-13 10:50 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun SignUp(onSignUpSuccess: (String, String) -> Unit, onSignUpFailure: () -> Unit) {
email과 password 값을 받아 검증하고, 반환해주는 것을 객체로 나눠서 구현하신 부분이 가독성에서 좋은 것 같아요!

2024-10-13 10:50 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                horizontalArrangement = Arrangement.SpaceBetween // 좌우로 균등하게 배치
저는 alignment와 arranmgement가 row와 column에 따라 다른게 너무 헷갈리더라고요.. 잘 몰라서 fillmax를 주고 align을 center로 맞추는 등 불필요한 작업들을 이렇게 SpaceBetween 같이 사용할 수 있다는 것을 배워갑니다!

2024-10-13 10:50 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                            context.startActivity(intent)  // Activity 시작
flags나 finish() 함수를 호출하지 않으면 stack이 쌓여서 MyActivity에 이전을 누르면 다시 돌아오는 걸로 알고 있어요! 
제가 놓친 부분이 있을 수도 있는데, 만약 MyActivity에서 뒤로가기 시에 해당 activity로 오지 않는다면 어느 부분에서 설정해주신 건지 궁굼해요!

2024-10-13 13:24 UTC, serioushyeon reviewed
세이호님 코드 구경왔습니다 ~~ 화이팅!! 🍀

2024-10-13 14:59 UTC, hyoeunjoo requested changes
고생 많으셨습니다ㅠㅠ 안드가 처음인 사람에게 얼마나 과제가 힘들게 느껴졌을지 누구보다 더더더 잘 알고 있습니다.. 시간이 촉박하셨음에도 불구하고 열심히 하신 부분들이 보여서 감동.. 앞으로 같이 홧팅하면서 성장해봐요!! 칠칠이조 최고!!

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +}
함수분리 좋은데요!

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun validateEmail(email: String): Boolean {
그니까여.. 저도 이번에 처음 알게됨 ^_^;;

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        }
태정오빠 코리에도 말했던 부분인데 만약 여러개의 데이터들을 넘겨줘야 한다면 하나하나 다 데이터를 써줘야하니까 더 불편해지겠죠..? 한 번에 보따리에 싸서 넘겨주면 더 편할테니까요 ㅎㅎ 그런 의미에서 Bundle에 대해서 알아보셨으면 좋겠어요

+) 이번주차에 배운 ViewModel을 이용해서 여러개의 데이터들 중 새로 바뀐 데이터만을 업데이트해서 넘겨줄 수 있는 엄청난 편리한 부분도 있답니다! 이건 나중에 우리 같이 써봐요!

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +        }
지금은 이런 흰색 텍스트만으로 나타내셨지만, 실제 ui에서는 텍스트 한 줄에서도 흰색과 회색으로 나눠져있어요!
물론, Row로 해서 흰색텍스트, 회색텍스트 로 배열해도 되겠지만!

만약 나중에 흰회흰으로 텍스트를 나타내야한다면? 총 글자수 중에서 2~6번째 텍스트만 볼드처리하고 색을 다양하게 내고싶다면?? 이를 여러곳에서 사용해야 한다면?? 
엄청 줄 수가 늘어나고 복잡해지겠죠ㅠㅠ Spannable에 대해서 알아보셔도 좋을 것 같아요!

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    if (password.length !in 8..20) return false
오!!코틀린 문법 잘 쓰셨는데요!?!  
그런데 8과 20은 코드를 쓴 사람이 아니라면 어..? 어떤 숫자를 나타내는거지? 싶으면서 이해하는데 조금 시간이 걸릴 수도 있습니다. 또한 만약에 비밀번호 길이가 변경됐다면 이 긴 파일 안에서 해당 부분을 찾아서 숫자를 변경해줘야되는 번거로움과 불안정성이 생기겠죠

```
   companion object {
        const val MIN_PASSWORD_LENGTH = 8
        const val MAX_PASSWORD_LENGTH = 20
    }
```

이렇게 상수화를 시키면 유지보수 측면에서 더 좋을 것 같아요! 한 번 알아보시겠어요?

2024-10-13 14:59 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +    val context = LocalContext.current
이번주에 배운 ViewModel기억나시나요?
2주차 과제에서는 해당 부분을 어떻게 ViewModel로 옮겨야할지 생각해보시면 좋을 것 같습니다 ㅎㅎ
지금과 어떤 부분이 달라졌고, 어떤 측면에서 더 좋아졌는지도 같이요!

2024-10-13 15:38 UTC, hyoeunjoo reviewed
2차로 달았슴다..~^^

2024-10-13 15:38 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                    }
헷! 여기 사이에도 | 이거 있지롱~
그리고 이제 과제 리팩토링하면 UI따라서 해야되는데 그때 이제 얇은 선들이 몇개 생기거든용?
Horizontal, Vertical Divider를 이용하면 될 것 같습니다 한 번 찾아보시겠어요??

그리고 현재 해당 함수안에 너무 많은 코드들이 있어서 보기가 살짝 어려운 것 같아요
점점 더 복잡하고 요소가 많은 UI일수록 밑으로 하염없이 스크롤을 해야 하는 문제가 생기겠죠..ㅠㅠ
이럴때 우리는 어디서부터 어디까지 밖으로 빼는게 좋을지에 대해 한 번 생각해보면 좋을 것 같아요 (저두 모름ㅋ 정답은 없습니다)

2024-10-13 15:38 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +
텍스트 필드가 여러 곳에서 반복되고 있죠? 그런 의미에서 따로 함수를 빼서 재사용하면 훨씬 코드도 간결해지고 보기도 쉬운 함수가 될 것 같아요. 이메일 텍스트필드와 비밀번호 텍스트필드를 따로 함수로 뺄 수도 있고, 하나의 함수로만 빼서 이메일과 비밀번호에 맞게 커스텀해서 사용할 수도 있겠죠

어떤 요소들을 빼서 인자로 넣을지는 고민을 해보는게 좋을 것 같습니다!

앗차차 그리고 TextField, OutlinedTextField, BasicTextField등 여러 종류가 있는데 각각의 속성에는 어떤것이 있고 어떤 경우에 어떤 텍스트 필드를 쓰면 좋을지에 대해서도 한 번 생각해보시는건 어떠신가용

2024-10-13 15:38 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                .background(Color.Gray.copy(alpha = 0.5f))
오홍 ㅎㅎ 약간의 투명도 디테일~~

2024-10-13 15:38 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +            text = "또는 다른 서비스 계정으로 가입",
스트링 추출은 제일 귀찮은 일이지만 기본적으로 꼭 해줘야하는 작업 중 하나.. 그 이유는 의진님이 잘 설명해주신 것 같아요 ㅎㅎ alt+Enter눌러서 String추출하기 누르면 좀 더 편하게 추출을 할 수 있습니당

2024-10-15 00:24 UTC, sayyyho commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +        }
처음 공부하는 입장이라 두 방법을 둘 다 써봤습니다!!

2024-10-15 00:50 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +            }
넵 다음부터는 선언형 UI의 장점을 활용하여 개발하겠습니다!!

2024-10-15 00:52 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                val password = intent.getStringExtra("password") ?: ""
감사합니다! 대체하겠습니다!

2024-10-15 00:56 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +        )
화면 종료하는 액션으로 대체하겠습니다!!

2024-10-15 01:03 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                singleLine = true,
res/values/strings.xml애 따로 분리해서 사용하겠습니다!!

2024-10-15 01:08 UTC, sayyyho commented on gradle/libs.versions.toml
앗 사용하지 않아 삭제 하겠습니다!

2024-10-15 01:11 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                    }
놓쳤던 부분 잡아주셔서 감사합니다! 수정했습니다!

2024-10-15 02:13 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        }
bundle 도입했습니다 감사합니당

2024-10-15 02:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                    }
Google에서는 [이와 같은 방법](https://github.com/google/accompanist/blob/6611ebda55eb2948eca9e1c89c2519e80300855a/permissions/src/main/java/com/google/accompanist/permissions/PermissionsUtil.kt#L99)으로 context에서 Acitivity를 사용한다고 하니 참고해보시면 좋을 것 같습니다.

2024-10-15 02:21 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +        }
찾아보니까 spnnable이 컴포즈보다 xml에서 많이 사용된다고 해서 AnnotatedString.Builder를 통해 흰색과 회색 구분지었습니다!

2024-10-15 02:31 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    if (password.length !in 8..20) return false
수정했습니다!

2024-10-15 02:31 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun validateEmail(email: String): Boolean {
앗 다음에는 꼭 써야겠다 ㅎㅎ

2024-10-15 02:32 UTC, sayyyho commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +                            context.startActivity(intent)  // Activity 시작
finish() 호출하도록 바꿨습니다! 덕분에 많이 배워갑니당ㅎㅎ

2024-10-15 02:34 UTC, merged

2024-10-16 11:31 UTC, jihyunniiii reviewed
리뷰 늦게 달아서 죄송해요 ㅠㅠ
일단은 읽어보시고 2주차 과제하실 때 반영해주시면 될 것 같아요!
고생하셨습니다!

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".MyActivity"/>
manifest의 exported 속성에 대해서 조금 공부를 해보시면 좋을 것 같아요!

2024-10-16 11:31 UTC, jihyunniiii commented on .gitignore
> +.idea/*
이게,, 왜 이랬지,, 하암,,,

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +                val email = intent.getStringExtra("email") ?: "test@test.test"
지금 email 이라는 값을 통해서 값을 주고 받았잖아요!
여기서 만약 email이라는 값이 아니라 누군가 잘못해서 EMAIL 을 통해 값을 주고 받으려 한다면 어떻게 될까요?
또 위와 같은 문제를 어떻게 해결할 수 있을까요!!

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +                    .clickable { },
사용하지 않는 clickable은 일단은 지워주셔도 될 것 같아요!
혹은 TODO 주석을 사용해보시는 것도 추천합니다.

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/MyActivity.kt
> +        Footer()
깔끔하네요 좋다잉 ~

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignInActivity.kt
> +    val snackbarHostState = remember { SnackbarHostState() }
요 둘의 차이점을 찾아보셔도 좋을 것 같아요!!

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                            putString("password", password)
data class를 사용하는 것도 좋아보여요!

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +                        Toast.makeText(application, "회원가입 성공!", Toast.LENGTH_SHORT).show()
요렇게 자주 사용되는 친구들은 확장함수로 빼두는 것도 좋아용!
추가로 kotlin에서 확장함수에 대해 알아보시는 것도 좋을 것 같네요~

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun Header() {
안드로이드에서는 Header보다 TopAppBar라는 이름을 씁니당
3주차 때 자세히 다룰게용

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +fun SignUp(onSignUpSuccess: (String, String) -> Unit, onSignUpFailure: () -> Unit) {
SignUp **화면**이라는 것이 네이밍에 담기면 좋을 것 같아요!
지금 네이밍으로는 그냥 회원가입을 해주는 함수인지 헷갈릴 수도 있으니까요!
제가 세미나 때 Composable 함수는 UI를 그리는 역할을 담당하고, 선언형 UI이기 때문에 어떤 것을 그릴지만 명시해주면 된다고 했던 거 기억하시나요?
그렇기 때문에 네이밍을 할 때도 무엇을 그릴것인지를 **명사 형태**로 작성한다고 생각하시면 조금 더 네이밍이 편해질 것 같네요!

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    return emailRegex.matches(email)
Regex 객체 생성은 CPU를 많이 소모하는 작업 중 하나입니다.
그렇기 때문에 이렇게 작성하게 되면 해당 함수를 실행시킬 때마다 객체가 생성되고, 이 때문에 CPU 성능을 많이 잡아먹겠죠??
그렇기 때문에 이런 작업은 싱글톤 패턴 등을 이용하여 관리하는 것이 좋습니다.

2024-10-16 11:31 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/SignUpActivity.kt
> +    }
companion object는 class 하단에 배치하는 것이 컨벤션입니다!