[feat] #3 - 2주차 과제 구현
AND-SOPT-ANDROID/seho-park pull request #4
Opened 2024-10-25 14:59 UTC by sayyyho

## Related issue 🛠
- closed #3 

## Work Description ✏️
- SAA 적용
- MVVM 적용
- BottomNavigation 적용
- 기타 수정

## Screenshot 📸

https://github.com/user-attachments/assets/ce768241-8faa-4f4f-a4e1-9f2adf34025d

## Uncompleted Tasks 😅
- [ ] 검색
- [ ] 기타 UI

## To Reviewers 📢

2024-10-27 10:40 UTC, imtaejugkim approved these changes
이번주에 우리 조원들 바빴던 것 같은데 끝까지 완수하시느라 고생하셨습니다! 코드 보면서 컴포넌트화 과정들 더 자세히 알아갈 수 있었던 것 같아요. 3주차는 저도 더 공부해서 좋은 코드리뷰 달 수 있도록 노력하겠습니다!

2024-10-27 10:40 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +                PosterRow(moviePosters = Posters, itemComposable = { poster, rank -> rank?.let {
컴포넌트화 해서 사용하셨군요! 제가 컴포넌트화를 잘 못시켜서 좋은 배움 얻어갑니다!

2024-10-27 10:40 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +    LazyRow(
팥장님의 이번 과제 의도인지는 모르겠지만, List 말고 pager 기능도 있더라구요! 데이터가 페이저 단위로 나뉘어져있어서 저는 이번 과제에 사용해보았습니다. 한번 확인해보시는 것도 좋을 것 같아요!

2024-10-27 10:40 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +            SignUpScreen(signViewModel = signViewModel, navController = navController)
저도 이렇게 하나의 뷰모델로 써야할지, 화면마다 뷰모델을 나눠서 써야할지 정말 고민 많이 했었던 것 같아요...! 하나의 뷰모델로 사용하니까 통일성이 생기는 것 같아 좋아보여요

2024-10-27 14:57 UTC, hyoeunjoo requested changes
과제가 많이 어려웠을텐데 고생 많으셨습니다ㅠㅠ 저도 넘 어려웠어요 ㅠ_ㅠ
아래에 조금 더 추가적으로 코드리뷰 달아놓을게요!

2024-10-27 14:57 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +val Posters = List(9) { R.drawable.bee }
여러 이미지가 필요한 경우에는 어떻게 하면 좋을까요?
이렇게 공통으로 같은 이미지를 만들어 놓은 경우에는 계속해서 그 이미지만 보이게 되겠죵

이미지 리스트를 하나 만든 뒤 세호님께서 아래 잘 만들어 놓으신 LazyRow에 리스트에서 이미지를 하나씩 꺼내서 넣어주기만 한다면!!? 쉽게 우리가 원하던 모습을 만들 수 있을 것 같아요 ㅎㅎ

2024-10-27 14:57 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
이건 어떤 용도인가요??

2024-10-27 14:57 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
저희 과제 부분에 맨 위 상단 배너는 무한으로 넘어가는 페이지더라구요 ㅎㅎ
이렇게 하면 옆으로 스크롤은 잘 되지만! 어떻게하면 사용자가 손을 안써도 무한대로 돌아갈 수 있을까요 ~.~

HorizontalPager에 대해서 한 번 찾아보세용!

2024-10-27 15:30 UTC, hyoeunjoo reviewed
위에 달았던 내용과 더불어서 조금 더 작성해보았습니다 ㅎㅎ!! 고생 많으셨습니다 완전!!!!

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    private val savedPassword = "password123"   // Mock password for sign-in validation
이 부분은 왜 필요한걸까용?

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
보통은 이런 상수부분은 코드의 맨 아래로 보냅니다 ㅎㅎㅎ
그리고 Email처럼 비밀번호도 따로 정규화 식을 만들어놓으면 더 편할 것 같다는 생각이 드네요!

그리고 또 위의 상수는 companion object로 아래는 object로 선언해주셨는데 그 둘의 차이는 뭘까요?

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
위에서 말씀드린 것처럼 이 부분을 하나의 함수로! 이메일로 하셨던 것처럼 할 수 있을 것 같아용

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +) {
입력형식이 유효하지 않으면 버튼이 유효하지 않게 만들어주는 로직을 추가해주시면 좋을 것 같아요!

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            if (email.isNotEmpty() && password.length in 8..20) {
이 부분은 뷰모델로 옮길 수 있을 것 같은데용?
뷰모델에 
`const val MIN_PASSWORD_LENGTH = 8
        const val MAX_PASSWORD_LENGTH = 20`이렇게 잘 선언해주셨던걸 이용해보세요!ㅎㅎ

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            } else null
이건 텍스트필드를 재사용하기 위해서 이렇게 하신건가요? 비밀번호 텍스트필드가 맞을때랑 아닐때 show/hide를 보여줄지 말지를 결정하는 부분같은데 사실 재사용에는 정답은 없습니다만 ㅠ_ㅠ 이 부분을 추가하면서까지 로그인과 패스워드 텍스트 필드를 같이 사용해야할지는 쪼금 더 고민을 해봐야하는 부분같아요! 물론 제 생각이 틀렸을 수도 있고 제가 세호님의 의도를 파악 못했을 수도 있습니다 ㅎㅎㅎ 어떤 의도였는지 여쭤봐도 될까용??

2024-10-27 15:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +}
SignUp에서도 많이 사용되는 부분인데 컴포넌트로 따로 분리하면 여러 부분에서 재사용 할 수 있으니까 중복을 방지할 수 있겠죠?!

2024-10-29 08:15 UTC, kez-lab reviewed
안녕하세요 세호님~!! 2주차 과제도 넘 고생 많으셨습니다. 
제가 저번주가 너무 바빠서 늦게 과제를 보게되어 정말 죄송합니다 😥

이번주 로직들 컴포넌트화가 잘되어있어서 UI가 머릿속에 잘 그려졌던 것 같아요!
다만 네이밍이나 에러처리 및 공통된 컴포저블을 유연하게 쓸 수 있는 방법을 더 고민해보시면 더더 좋은 코드가 될 것 같습니다.

중간중간에 의미없는 주석들도 더 의미있게 만들어보면 좋을 것 같아요

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +            SignUpScreen(signViewModel = signViewModel, navController = navController)
통일성이 항상 좋은건지 의문을 가져봐도 좋을 것 같아요, 하나의 클래스 내부에서 여러개의 상황에 대응하려면 그만큼의 분기처리와 예외상황까지 생각해야할 수 있을 것 같아요 ㅎㅎ

물론 공통화가 나쁘다는건 절대 아닙니다, 비즈니스 로직의 독립성 측면에서 공통화를 한다는 것은 굉장히 안정적인 소프트웨어를 구축하는데에 큰 역할을 하니까요

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +            SignUpScreen(signViewModel = signViewModel, navController = navController)
네비게이션 활용 아주 굿!
근데 SignViewModel은 인자로 넘겨받고 navController는 내부에서 생성하셨는데 기준이 어떻게 되는지 궁금하네요

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MainScreen.kt
> +) {
AddItem 이란 이름을 보았을 때 어떤 의미를 가지고 있는지 잘 모르겠습니다
조금 더 특성을 잘 나타내는 이름으로 변경해보면 어떨까요?

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MainScreen.kt
> +) {
RowScope의 확장으로 만드신 이유도 궁금합니다.

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/MainScreen.kt
> +        colors = NavigationBarItemDefaults.colors(
currentDestination?.hierarchy?.any {
            it.route == item.route
        } == true
        
이 부분을 인자로 받아오는 것은 어떠실까요?

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
itemsIndexed 를 활용해도 좋을 것 같네요

2024-10-29 08:15 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +                        Text(text = if (isPasswordVisible) "Hide" else "Show", color = Color.White)
찾았습니다 !!
```suggestion
                    TextButton(onClick = onPasswordToggle?.invoke()) {
                        Text(text = if (isPasswordVisible) "Hide" else "Show", color = Color.White)
```

2024-10-30 09:55 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +    LazyRow(
오 Pager! 처음 알았습니다! 감사합니다!

2024-10-30 10:03 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
홈 스크린에서 각 포스터 위 설명 텍스트로 사용하는 용도입니다!

2024-10-30 10:05 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
네 알겠습니다!!

2024-10-30 10:06 UTC, sayyyho commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    private val savedPassword = "password123"   // Mock password for sign-in validation
아 테스트 용도로 두었다가 못 지웠네요!! 감사합니다!!

2024-10-30 10:38 UTC, sayyyho commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
넵 맨 아래로 보내고 비밀번호도 정규화 식을 만들어볼게용!! object 부분은 외부에서 util로 사용할 수 있다고 생각해서 사용했습니다!

2024-10-30 10:39 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +) {
넵 추가하겠습니다!

2024-10-30 10:40 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            if (email.isNotEmpty() && password.length in 8..20) {
감사합니다!! 뷰모델로 이동시키겠습니당

2024-10-30 10:52 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            } else null
텍스트 필드를 비밀번호 필드인지 여부에 따라 재사용 가능하도록 구성하려고 했었는데, 역할에 따라 조금 더 분리를 해야겠다고 생각이 드네요.

2024-10-30 10:56 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +}
넵 이번에 컴포넌트로 분리해서 사용해보도록 하겠습니다!! 감사합니다!

2024-10-31 03:53 UTC, jihyunniiii reviewed
고생하셨습니당 ~

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +val categories = listOf("뉴클래식", "드라마", "예능", "영화", "애니", "해외시리즈")
추가로 해당 값들은 뷰모델을 통해서 관리해도 좋을 것 같네요!

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +val roundedCorner = RoundedCornerShape(3.dp)
그리고 어떠한 값들을 전역변수로 선언하는 것이 좋은지 고민을 해보셔도 좋을 것 같아요!

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +        items(categories.size) { index ->
categories 자체를 인자로 받을 수도 있습니당

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +                    .height(400.dp)
aspectratio에 대해 찾아보세요!
그리고 이미지의 크기 때문에 Box로 감싼 건가요??
Box를 없애고 Image의 Modifier를 활용하는 방법도 있을 것 같네요

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
> +        )
web에서는 footer라는 말을 사용하지만 앱에서는 해당 컴포넌트를 BottomNavigation이라고 불러요!

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
> +        )
그리고 아래에 있는 enum class를 활용해서 만들 수도 있을 것 같은데요!?

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +fun SignUpScreen(signViewModel: SignViewModel, navController: NavController) {
하위 컴포저블에 NavController를 전달하는 건 권장하는 방식이 아닙니다. (단일 책임 원칙 등에 의해서요. 이렇게 하면 이 스크린이 네비게이션과 관련된 책임을 가지게 되니까요)
NavController 자체를 인자로 넘기기보다는 사용되는 부분을 함수화 하여 함수를 인자로 넘기는 게 좋겠네요.

2024-10-31 03:53 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
클래스 내부에 object를 선언한 이유가 있나요?
전역적으로 사용하시려면 class 외부에 object 객체를 선언해야합니다!

2024-11-01 05:02 UTC, sayyyho commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
해당 부분은 더 공부해서 수정하도록 하겠습니다. 우선은 companion object 하나에 관리해도 될까요?

2024-11-01 05:14 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +fun SignUpScreen(signViewModel: SignViewModel, navController: NavController) {
아 단일 책임 원칙을 따르는군요!! 함수화 시켜서 수정하겠습니다!!

2024-11-01 05:39 UTC, sayyyho commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
> +        )
enum class로 보완했습니다!

2024-11-01 05:48 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +                    .height(400.dp)
UI 구현쪽에 생각이 짧았네요! 수정 완료했습니다!!

2024-11-01 12:42 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +        items(categories.size) { index ->
리스트를 인자로 삼아서 할 수 있군요! 감사합니다!

2024-11-01 12:45 UTC, sayyyho commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +                        Text(text = if (isPasswordVisible) "Hide" else "Show", color = Color.White)
감사합니다! 제안해주신 방법으로 수정했습니다!

2024-11-01 12:46 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +val roundedCorner = RoundedCornerShape(3.dp)
넵 앞으로 고민하고 진행하겠습니다!

2024-11-01 12:47 UTC, sayyyho commented on app/src/main/java/org/sopt/and/home/HomeScreen.kt
> +}
이런 좋은 방법이!! 수정했습니다!

2024-11-01 12:55 UTC, sayyyho commented on app/src/main/java/org/sopt/and/MainScreen.kt
> +        colors = NavigationBarItemDefaults.colors(
제안 감사합니다! 수정했습니다!

2024-11-01 12:56 UTC, sayyyho commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +            SignUpScreen(signViewModel = signViewModel, navController = navController)
급하게 코드를 짜느라 고려를 못했습니다! 리팩토링 진행하겠습니다!

2024-11-01 13:01 UTC, sayyyho commented on app/src/main/java/org/sopt/and/MainScreen.kt
> +) {
BottomNavItem으로 직관적으로 수정했습니다! Row Scope의 추가적인 배치를 위해서 사용했습니다!

2024-11-01 13:37 UTC, merged