Week3
AND-SOPT-ANDROID/seho-park pull request #6
Opened 2024-11-01 14:57 UTC by sayyyho

## Related issue 🛠
- closed #5 

## Work Description ✏️
- 뷰 스케치
- 공통 요소 컴포넌트화
- UI 흐름 설계

## Screenshot 📸
https://sayyyho.notion.site/3-131059afc20e80e39e69d3165cbe096b?pvs=73

## Uncompleted Tasks 😅
- [ ] UI 구현도
- [ ] 코드 리팩토링

## To Reviewers 📢
이번 과제에서 특히 signup과 signin 부분 컴포넌트화를 노력했습니다. 컴포넌트화하는 과정이 쉽지는 않았지만, 중복되는 UI를 빼서 관리할 수 있는 점을 배워갑니다.

2024-11-03 10:59 UTC, imtaejugkim approved these changes
제가 미처 하지 못한 컴포넌트 부분까지 배울 수 있었습니다! 머나 먼 컴포즈 능력자가 되어 가는길... 같이 화이팅해요!

2024-11-03 10:59 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            )
기존 textField에서 좀 더 구체화 된 것을 확인할 수 있었습니다!

2024-11-03 10:59 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +                    Toast.makeText(context, "회원가입 실패: 입력 정보를 확인해주세요.", Toast.LENGTH_SHORT).show()
화면 내에서의 컴포넌트 말고, Toast같은 다른 화면에서도 쓰일 가능성이 있는 것들은 확장함수화로 전체 컴포넌트화가 가능할 것 같아요!

2024-11-03 10:59 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/components/SignTextField.kt
> +    showHint: Boolean = false,  // 추가된 파라미터
넘겨주는 인자가 true로 설정되어있는데 다시 false로 초기화 하는 것 같아요! 제가 맞는 답인지는 모르겠지만, 통일 시키는 것도 괜찮을 것 같아요!

2024-11-03 10:59 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/components/SignTopBar.kt
> +    }
topBar 까지 컴포넌트화가 가능하군요..! 저도 적용시켜보겠습니다

2024-11-03 13:44 UTC, hyoeunjoo requested changes
고생많으셨습니다!! 이제 벌써 4주차인데 이번주도 화이팅..>_<!!

2024-11-03 13:44 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/components/SignTopBar.kt
> +
실제 앱에서는 폰트 색이 다른데 색같은 경우는 어떻게 적용하면 좋을까요! 한 번 시도해보셔도 좋을 것 같습니다!
그리고 이 부분은 계속 반복되는 부분이니까 저같은 경우에는 확장함수로 한 번 빼보는 경험을 해봤어요 ㅎㅎ

2024-11-03 13:44 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/components/SignTopBar.kt
> +    }
어떻게 보면 컴포넌트를 분리한다는게 재사용을 위한건데 이렇게 분리를 하면 SignUp과 SignIn화면에서만 사용을 할 수 있고 더이상 다른 화면에서 재사용하기가 조금 힘들어 보이는 것 같아요..!!!

2024-11-03 13:44 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/components/SignTopBar.kt
> +}
이 부분을 따로 함수로 빼서 SignTopBar에서 사용하면 같은 형식(박스의 모양..등)을 가졌지만 다른 텍스트나 이미지를 넣어서 재사용하고 싶을 때 사용하기가 조금 힘들것 같아요..ㅠㅠ 함수화를 통해 너무 깨끗해진 코드는 좋습니다!! 그치만 컴포넌트를 분리한다는 의미에 맞게 리팩토링 해보시면 재사용이 가능한 더더 확장성 높은 좋은 코드가 될 것 같은데용??

2024-11-03 13:44 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
>              )
좋은데요잉~~!! 깔끔깔끔!

2024-11-03 13:44 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            Spacer(modifier = Modifier.height(30.dp))
SignUpHeader와 SignUpTopBar의 차이가 뭘까요?? 함수명만 봐서는 그 둘의 차이점을 알기가 조금 불명확한 것 같습니다!

2024-11-06 09:54 UTC, jihyunniiii reviewed
UI 설계를 하신 내용이 첨부되지 않아 확인을 못 했는데, 나중에 시간 남으실 때 첨부해주시면 좋을 것 같아요 ~
수고하셨습니다 !

2024-11-06 09:54 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/components/SignButton.kt
> +            coroutineScope.launch {
coroutineScope로 감싼 이유가 무엇인지 궁금합니다.

2024-11-15 10:58 UTC, merged