Week4
AND-SOPT-ANDROID/seho-park pull request #8
Opened 2024-11-15 14:59 UTC by sayyyho

## Related issue 🛠
- closed #7 

## Work Description ✏️
- 유저등록 API 연동
- 로그인 API 연동
- 취미조회 API 연동

## Screenshot 📸
<img src="" width="360"/>

Uploading 화면 

https://github.com/user-attachments/assets/8844e9b0-c971-42a9-972c-21817ce7bc0a

## Uncompleted Tasks 😅
- [ ] Task1

## To Reviewers 📢

2024-11-17 08:42 UTC, hyoeunjoo requested changes
4주차 서버통신 많이 힘들었을텐데 고생 많았습니다ㅠㅠ
합동세미나도 화이팅!

2024-11-17 08:42 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/api/Auth.kt
> +
다른 서비스라면 다른 파일로 분리하는게 나을 것 같아요
아니면 같은 파일명 Auth에 맞춰서 AuthService로 한 뒤에 같은 서비스 내에 두개의 함수를 넣는 방법도 있겠죠?

```
interface AuthService {
    @POST("/user")
    suspend fun postUserRegistration(
        @Body userRequest: RequestUserRegistrationData
    ): Response<ResponseUserRegistration>

    @POST("/login")
    suspend fun postLogin(
        @Body loginRequeset: RequestLoginData
    ): Response<ResponseLogin>
}

```
이런 식으루요!

2024-11-17 08:42 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/dto/Auth.kt
> +)
DTO같은 경우는 이름에 Dto라고 명시해주는 것이 좋습니다
또한 Response, Request등을 보통은 다른 파일로 빼는 편입니다.

```suggestion
@Serializable
data class RequestUserRegistrationDto(
    @SerialName("username")
    val userName: String,
    @SerialName("password")
    val password: String,
    @SerialName("hobby")
    val hobby: String
)

@Serializable
data class ResponseUserRegistrationDto(
    @SerialName("result")
    val result: ResultUserNo
)

@Serializable
data class ResponseUserRegistrationDto(
    @SerialName("no")
    val no: Int
)
```

이런식으로요! 각각 Dto는 다른 파일에 넣어주시는게 조금 더 좋을 것 같습니다.
그렇게 하면 주석으로 해당 Dto들을 나눠주는 것도 필요 없겠죠?

2024-11-17 08:42 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
> +@SuppressLint("UnrememberedMutableState")
이건 왜 사용하신건가용?

2024-11-17 08:42 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +) {
컴포저블 함수가 뷰모델을 인자로 받게 되면 해당 스크린은 뷰모델에 강하게 결합되겠죠? 그러면 컴포저블 함수의 재사용을 제한하는 경우가 생길 수 있습니다. 또한 UI와 비지니스 로직 간의 경계가 흐려질 수도 있겠습니다!

2024-11-17 08:42 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
이건 서버에서 검증해주는 부분이라 여기서는 따로 필요하지 않을 것 같습니다!
서버에서 내려주는 에러코드를 통해 에러핸들링을 해보시는 것도 좋을 것 같아용

2024-11-17 12:57 UTC, imtaejugkim approved these changes
4주차 정말 고생하셨습니다..! 한주한주가 해당 주가 제일 어렵다고 하는 갱신하는 주차인 것 같네요...ㅠㅠ 세미나 때 배운 통신 바탕으로 잘 구현해주신 것 같습니다! 합세동안 저희 배운 코드 바탕으로 열심히 협업해봐요 아자아자~!

2024-11-17 12:57 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/api/Hobby.kt
> +}
현재 명세서에는 이렇게 Header를 직접 명시해서 보내는 것으로 나와있지만, 실제 프로젝트에서는 interceptor에 토큰을 정의하는 방법도 많이 사용하더라구요! 한번 찾아보시는 것도 좋을 것 같아요!

2024-11-17 12:57 UTC, imtaejugkim commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_hobby_hint">취미를 입력해주세요.</string>
같은 값으로 사용할 수 있을 것 같아요!

2024-11-17 12:57 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +    }
저도 클라이언트에서 예외처리를 진행했지만.. 명세를 확인해보니 검증이 있더라구요!
오류 코드에 따라 예외처리 추가하면 좋을 것 같아요

2024-11-17 12:57 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/viewmodel/SignViewModel.kt
> +                    } ?: onFailure("서버 응답이 비어있습니다.")
sharedpreference 에 토큰을 저장하는 방법이군요! 토큰을 저장하고 사용하는 코드는 추후에 반복되는 header나 표시하는 작업에서도 쓰일 가능성이 있어 객체화 시켜도 좋을 것 같아용

2024-11-17 12:57 UTC, imtaejugkim commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
>              fontWeight = FontWeight.Bold,
hobby 가 비어있을 때 sport로 명시하신 이유가 있을까요?

2024-11-20 00:45 UTC, kez-lab reviewed
안녕하세요 세호님!! ㅠㅠ 넘 늦어서 죄송합니다!
뒷 부분을 못봐서... 혹시나 추가적으로 궁금한 부분 있으면 언제든 답글 남겨주세요!

4주차도 고생많으셨습니다!

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/components/SignButton.kt
>  ) {
이 주석을 추가하게 되신 히스토리가 궁금합니다.

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/dto/Auth.kt
> +)
아마 패키지명이 dto여서 dto를 붙이는 것을 추천해주신 것 같아요, 이 부분은 추 후 팀 컨벤션을 세우고 각 레이어에 알맞는 suffix를 붙여주면 좋을 것 같습니다.

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/myinfo/MyScreen.kt
>          Spacer(modifier = Modifier.height(20.dp))
인자로 넘기는 경우 최신 값을 전달한다라기 보다는 정확히는 state인 hobby를 전달해서 항상 최신값으로 리컴포지션을 보장함 이 맞을 것 같아요

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +) {
굿! 다만 저는 Screen단은 어느정도 큰 범주의 UI라고 생각해서 나쁘지는 않다고 보는 입장이긴합니다.
즉 SignInScreen을 다른 ViewModel을 참조하여, 혹은 ViewModel 없이 재활용하는 경우는 없을 것 같습니다.

물론 컴포넌트단에서는 금물이지만요 하핳

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
>              Spacer(modifier = Modifier.height(20.dp))
띄어쓰기가 있네요

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            }
요 글에 다양한 확장함수가 있던데 참고해보면 좋을 것 같아요 ㅎ.ㅎ
Medium: https://proandroiddev.com/top-5-extension-functions-every-jetpack-compose-developer-should-have-cbf2c50d557c

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +                            }
coroutineScope.launch 는 기본적으로 어떤 스레드인가요?

2024-11-20 00:45 UTC, kez-lab commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +                    }
요기도! Context Switching은 비용이 많이 드는 작업이니 항상 유의해서 사용해보면 좋을 것 같아요, 꼭 Context Switching이 필요한 상황인지..!

2024-11-20 01:36 UTC, jihyunniiii reviewed
고생하셨습니다 ~ 합동 세미나도 파이팅 !

2024-11-20 01:36 UTC, jihyunniiii commented on app/build.gradle.kts
> +    id("kotlin-kapt")
id와 alias의 차이점은 무엇일까요!

2024-11-20 01:36 UTC, jihyunniiii commented on app/build.gradle.kts
> +    implementation(libs.androidx.hilt.navigation.compose)
힐트를 사용하셨네요! 힐트를 사용했을 때의 이점은 뭘까요?

2024-11-20 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/api/Api.kt
> +    @Provides
@Provides와 @Binds의 차이는 뭘까요?

2024-11-20 01:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/dto/Auth.kt
> +data class ResponseUserRegistration(
지금 보면 응답 객체에서 동일한 형태가 사용되는데요, 이 경우 Base가 되는 Response를 만들어서 사용할 수도 있습니다!

2024-12-08 08:34 UTC, merged